name: Build and Push Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: stifskere/portfolio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Just
        run: |
          curl -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build Project
        id: build
        run: |
          image=$(IMAGE_TAG="$REGISTRY/$IMAGE_NAME" just build)
          echo "image_tag=$image" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        if: success()
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login "$REGISTRY" -u "${{ github.actor }}" --password-stdin

      - name: Push Image
        if: success()
        run: |
          docker push "${{ steps.build.outputs.image_tag }}";


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: DEPLOYMENT

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Just
        run: |
          curl -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      - name: Setup Kubeconfig
        working-directory: terraform
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > "./kube-config"
          chmod 600 "./kube-config"

      - name: Compute Project Version
        id: version
        run: |
          version="$(just info version)";
          echo "project_version=$version" >> "$GITHUB_OUTPUT"

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config='endpoints={s3="${{ secrets.TF_BACKEND_S3_ENDPOINT }}"}' \
            -backend-config="bucket=${{ secrets.TF_BACKEND_S3_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_BACKEND_S3_KEY }}" \
            -backend-config="region=${{ secrets.TF_BACKEND_S3_REGION }}" \
            -backend-config="access_key=${{ secrets.TF_BACKEND_S3_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.TF_BACKEND_S3_ACCESS_KEY_SECRET }}"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="cluster={
              kubeconfig = \"./kube-config\",
              deployment_tag = \"$REGISTRY/$IMAGE_NAME:${{ steps.version.outputs.project_version }}\"
            }" \
            -var='cloudflare={
              api_token = "${{ secrets.TF_VARS_CLOUDFLARE_API_KEY }}",
              target_zone = "${{ secrets.TF_VARS_CLOUDFLARE_TARGET_ZONE }}",
              target_records = ${{ secrets.TF_VARS_CLOUDFLARE_TARGET_RECORDS }}
            }'
